### ISSUE TITLE
Player is stuck and freeze sometime 

### ISSUE THREAD

**Issue by ziacto** [anthorlop/AJCPlayer#1]
Player is stuck and freeze sometime when there is no active live hls feed and only way to stop is force quite and even player.release is not helpful and PlayerEventListener is not worked as expected on error and only loading view showing all the time and how i can fix this issue.  Thanks

**Comment by ajhormigolopez** [comment]
Could you send me please the video url that you can't play to test it.

**Comment by ziacto** [comment]
This is the url and its playing but the problem is if streamer is offline and there is no way to handle the situation and PlayerEventListener is not updating the onError method because player keep loading and sometime just freeze the app. 
udp://@224.1.1.1:1234 

My suggestion is if there is no stream available or url is not valid it should update onError method and release the player. 
  

But i must say your player video quality is much better other player available on android platform even better then official vlc and jw player. I tried many players but i found this one much better.

**Comment by anthorlop** [comment]
I'm going to have a look the issue between this afternoon and tomorrow. I will let you know when is ready

**Comment by anthorlop** [comment]
Hi! I have created a beta versión of AJCPlayer. You can test ir changing maven URL from master to develop in build.gradle file and updating player dependency to 1.0.1.

Finally you can add a new PlayerEventListener and finish the activity or do whatever you want if you implement onError method.

**Comment by ziacto** [comment]
Hi Antonio. 
Error:Could not find es.lombrinus.projects.mods:AJCPlayer:1.0.1.
Required by:
    AJCPlayer:app:unspecified
I got this error. Can you share player source code or either you can sell. Thanks

**Comment by anthorlop** [comment]
Are you changed Maven repository url?

Use http://github.com/anthorlop/mvn-android/raw/develop/ instance of https://github.com/anthorlop/mvn-android/raw/master/

**Comment by ziacto** [comment]
Page not found, i think its a private repository.

**Comment by anthorlop** [comment]
I've uploaded the code

**Comment by ziacto** [comment]
Use http://github.com/anthorlop/mvn-android/raw/develop/ instance of https://github.com/anthorlop/mvn-android/raw/master/
These url are not working. i can not access on my side.

**Comment by anthorlop** [comment]
Ok. I'll try to publish code to master as soon as possible

**Comment by anthorlop** [comment]
Done

**Comment by ziacto** [comment]
http://github.com/anthorlop/mvn-android/raw/develop/ 
https://github.com/anthorlop/mvn-android/raw/master/ 

Still not a valid URLS. 

Player still crashed instead call onerror method if i pass url like abc.com/abc.mp4 which does not exists. Thanks

**Comment by anthorlop** [comment]
https://github.com/anthorlop/mvn-android/raw/develop/
https://github.com/anthorlop/mvn-android/raw/master/

URLs work for me. And master URL hasn't changed.

**Comment by ziacto** [comment]
Because your master urls are private repository and thats why no one can access until you made it public or you give me permission by adding me into this code. Meanwhile here is picture that i can not access your code.
https://ibb.co/kP54CR 

Thanks in Advance

**Comment by anthorlop** [comment]
You can't access to this url's in your browser, so have to upgrade your player version in your build.gradle file to use it. I can't open this url's in browser as well.

**Comment by ziacto** [comment]
i did upgrade and its keep loading again and still not giving me result. OnError Method is not called when wrong or bad stream url passed to player so in that case i can use backup  url to maintain the stream. I downloaded new project and pass the random url and its crashed again instead calling of onError. When i passed valid url then onPlayBegins works but not onError. So need to fix crashing player and on run time changing the url. This what i need. If you can share source code. It will be great help. Thanks

**Comment by anthorlop** [comment]
I found the problem, the error event was not being triggered when the video URL was called to get the contentType. I've created 1.0.2 player version and uploaded example app changes, can you try it again? I hope it works

**Comment by ziacto** [comment]
Good to know. Let me check. Thanks

**Comment by ziacto** [comment]
player stops playing udp://@224.1.1.1:1234 . Always throw an error. if i can get the source code it will great help so i can change in as per my need. Meanwhile here is logs

E/ccl_ChromeCastPlayer: Error isRemoteMediaLoaded
D/ERROR: VIDEO_0_Video not available
E/MediaPlayer: Attempt to perform seekTo in wrong state: mPlayer=0x0, mCurrentState=1
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: stop called in state 0
E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
E/PlayerControlBarManager: Asset VIDEO: 0-udp://@224.1.1.1:1234
E/MediaPlayer: pause called in state 0
D/OpenGLRenderer: endAllStagingAnimators on 0xf3daf200 (RippleDrawable) with handle 0xef33fac0
E/ccl_ChromeCastPlayer: Error isRemoteMediaLoaded
E/MediaPlayer: Attempt to perform seekTo in wrong state: mPlayer=0x0, mCurrentState=0
E/MediaPlayer: stop called in state 0
E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer

Best Zia

**Comment by anthorlop** [comment]
I've added an URL validation before checking video contentType and maybe your URL format is not valid and stops playing. Let me check it because I think validation is no longer necessary.

**Comment by ziacto** [comment]
Ok. waiting for your reply.

**Comment by anthorlop** [comment]
I've removed URL validation and I got an IllegalArgumentException (unexpected url) when URL is not valid (I use okhttp library). I've caught the exception and I hope your video URL works. I've just uploaded version 1.0.3.

**Comment by ziacto** [comment]
Same Problem 

E/MediaPlayer: Error (-38,0)
E/PlayerControlBarManager: Asset VIDEO: 2131755179-udp://@224.1.1.1:1634
D/ERROR: VIDEO_2131755179_java.lang.IllegalArgumentException: unexpected url: udp://@224.1.1.1:1634
E/ccl_ChromeCastPlayer: Error isRemoteMediaLoaded

**Comment by anthorlop** [comment]
Your URL is not valid. You have to get contentType of the video. The okhttp library doesn't work with this type of url, is not my fault. I'm not going to share the code for now, we can discuss about it in the future. Send me a solution to check your URL correctly and I'll add the code to video player.

**Comment by ziacto** [comment]
is your code available for sale if you can not share free?
Also i need to modify the code for full screen. right now its not there. except open new activity. player need to provide this feature as well.

**Comment by anthorlop** [comment]
Try to send an Asset to video player with localPath parameter as true to play local files.

I've sent you an email
